### ISSUE TITLE
ajax rating and comment

### ISSUE THREAD

**Issue by esginmurat** [MacWarrior/clipbucket-v5#105] opened 2019-08-24 14:39 UTC
Hello. Dear admin thanks for clipbucket 5.
i have this error. my comment function and rating function not working :(
please help me.
(ubuntu 18.04.3, php 7.2)
![error](https://user-images.githubusercontent.com/17769013/63638862-0d2da500-c696-11e9-8105-0e86a29a2070.jpg)

**Comment by esginmurat** [comment] 2019-08-24 15:16
.... and add new language functions doesnt work. (/admin_area/language_settings.php) 
![languageerror](https://user-images.githubusercontent.com/17769013/63639401-3dc40d80-c69b-11e9-8fc6-30e6e12cf12f.jpg)

**Comment by MacWarrior** [comment] 2019-08-24 17:18
Hi,

Thanks for report !

1) I can't reproduce this error ; compared to the default config, what did you changed ?
I found a DB structure error and fixed id ; can you try with latest commit (and don't forget to apply the SQL request about it)

2) Can you copy/paste the php error 500 ? (From your php error log file)

**Comment by esginmurat** [comment] 2019-08-24 21:19
Greetings, respectable manager. Thank you for responding. 

I did not modify any files. Clean installation.

The error code is here:
---
[24/Aug/2019:18:29:40 +0200] "POST /admin_area/ajaxLang.php HTTP/1.0" 500 1116 "https://videoizlepaylas.com/admin_area/language_settings.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
---
Regards,

**Comment by MacWarrior** [comment] 2019-08-24 23:13
Hi,

Thanks for your response ; but this is the access log and not error log

From my side ; with dev mode enabled, I don't get an error 500 but this is the response from the ajax call  : 
`<br />
<b>Fatal error</b>:  Uncaught ErrorException: Client error: `POST http://translate.google.cn/translate_a/single?client=t&amp;hl=en&amp;dt=t&amp;sl=en&amp;tl=de&amp;ie=UTF-8&amp;oe=UTF-8&amp;multires=1&amp;otf=0&amp;pc=1&amp;trs=1&amp;ssel=0&amp;tsel=0&amp;kc=1&amp;tk=790557.664419` resulted in a `400 Bad Request` response:
&lt;!DOCTYPE html&gt;&lt;html lang=en&gt;&lt;meta charset=utf-8&gt;&lt;meta name=viewport content=&quot;initial-scale=1, minimum-scale=1, width=de (truncated...)
 in /home/http/clipbucket-test/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:324
Stack trace:
#0 /home/http/clipbucket-test/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(361): Stichoza\GoogleTranslate\TranslateClient-&gt;getResponse('Please enter a ...')
#1 /home/http/clipbucket-test/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(185): Stichoza\GoogleTranslate\TranslateClient-&gt;instanceTranslate('Please enter a ...')
#2 /home/http/clipbucket-test/includes/classes/ in <b>/home/http/clipbucket-test/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php</b> on line <b>324</b><br />
`

The whole "auto-translate" system seems to be KO

Will try to find a workaround asap

**Comment by esginmurat** [comment] 2019-08-25 08:05
Hello dear owner.
thanks for reply.

here my error:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ErrorException: Client error: `POST http://translate.google.cn/translate_a/single?client=t&hl=en&dt=t&sl=en&tl=tr&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=790557.664419` resulted in a `400 Bad Request` response:\n<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=de (truncated...)\n in /var/www/vhosts/videoizlepaylas.com/httpdocs/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:324\nStack trace:\n#0 /../httpdocs/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(361): Stichoza\\GoogleTranslate\\TranslateClient->getResponse('Please enter a ...')\n#1 /.../httpdocs/includes/classes/GTvendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(185): Stichoza\\GoogleTranslate\\TranslateClient...\n', referer: ../admin_area/language_settings.php
--
regards..

**Comment by MacWarrior** [comment] 2021-08-11 13:04
Hello, 

As this issue now exists in a dedicaced one (#168), I close this one which was first about comment and voting issue.

Best regards,
MacWarrior.

**Closed by MacWarrior** 2021-08-11 13:04 UTC
Labels: bug, question
