### ISSUE TITLE
"loading Creating database structure..." loops.

### ISSUE THREAD

**Issue by webzxw** [MacWarrior/clipbucket-v5#257] opened 2023-04-09 00:11 UTC
[IMAGE](https://i.ibb.co/zNpNzsN/Capture-d-cran-du-2023-04-09-02-09-30.png)

i don't understand why

**Comment by MacWarrior** [comment] 2023-04-09 07:09
Hello @webzxw,

Thanks for your issue, you must have an SQL error : can you please check your PHP log file and send me your SQL error back ?

Thanks by advance, 
Best regards,
MacWarrior.

**Comment by webzxw** [comment] 2023-04-09 13:36
> Hello @webzxw,
> 
> Thanks for your issue, you must have an SQL error : can you please check your PHP log file and send me your SQL error back ?
> 
> Thanks by advance, Best regards, MacWarrior.

[Sun Apr 09 15:32:39.663288 2023] [php:error] [pid 15001] [client ::1:57296] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'cb_action_log' already exists in /var/www/html/clipbucket/cb_install/ajax.php:101\nStack trace:\n#0 /var/www/html/clipbucket/cb_install/ajax.php(101): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/clipbucket/cb_install/ajax.php on line 101, referer: http://localhost/cb_install/

**Comment by MacWarrior** [comment] 2023-04-09 13:42
Hello @webzxw , 

Thanks for reply ; did you tried installing multiple times ?
Looks like this table already exists on your DB ; can you retry with another DB prefix (like cb2_) ?

Best regards,
MacWarrior.

**Comment by webzxw** [comment] 2023-04-09 13:47
> Hello @webzxw,
> 
> Thanks for your issue, you must have an SQL error : can you please check your PHP log file and send me your SQL error back ?
> 
> Thanks by advance, Best regards, MacWarrior.

When I change the prefix it brings me back to the main download page

[VIDEO](https://streamable.com/8sbg45)

**Comment by webzxw** [comment] 2023-04-09 14:01
> Hello @webzxw ,
> 
> Thanks for reply ; did you tried installing multiple times ? Looks like this table already exists on your DB ; can you retry with another DB prefix (like cb2_) ?
> 
> Best regards, MacWarrior.

Hello @MacWarrior 

i change prefix but still a bug [HERE](https://streamable.com/8sbg45)

**Comment by MacWarrior** [comment] 2023-04-09 14:14
Hi @webzxw ,

Thanks for reply, it looks like an old bug I though was fixed... I'll try to reproduce asap...

Best regards,
MacWarrior

**Comment by MacWarrior** [comment] 2023-04-09 19:28
Hi @webzxw, 

Do you have any PHP/SQL error in your PHP log file ?
Or do you have any JS error in your browser console during installation process ?

Thanks by advance,
Best regards,
MacWarrior.

**Comment by MacWarrior** [comment] 2023-04-10 10:29
Hi @webzxw, 

I tested a full clean install on Debian10 / PHP 8.0.28 / MariaDB 10.3.38, on browser Brave 1.50.114
Did you manually configured your server, or did you an installation script I provide ?
Installation process is mainly done in JS, so issue can be related with your browser / browser version / browser extensions
Can you retry with the same browser and check for JS errors in browser console ?
And retry with another browser ?

Don't forget to change DB prefix between each test, or manually clean your DB...

Thanks by advance,
Best regards,
MacWarrior.

**Comment by webzxw** [comment] 2023-04-10 12:30
> Hi @webzxw,
> 
> I tested a full clean install on Debian10 / PHP 8.0.28 / MariaDB 10.3.38, on browser Brave 1.50.114 Did you manually configured your server, or did you an installation script I provide ? Installation process is mainly done in JS, so issue can be related with your browser / browser version / browser extensions Can you retry with the same browser and check for JS errors in browser console ? And retry with another browser ?
> 
> Don't forget to change DB prefix between each test, or manually clean your DB...
> 
> Thanks by advance, Best regards, MacWarrior.

i installed with your installation script with my ubuntu v22.04, i will test later because i rage quit and deleted the website, thanks for support

**Comment by MacWarrior** [comment] 2023-04-11 16:19
Hi @webzxw, 

I haven't tested install on Ubuntu 22.04 ; adding it to my todo list
I pushed a little fix on installation process, nothing related apparently, but as long as I don't reproduce your issue...

Best regards,
MacWarrior.

**Comment by alex4984191** [comment] 2023-06-15 18:10
Hi!
I have error in structure.sql
ALTER TABLE `{tbl_prefix}languages`
    DROP COLUMN language_code,
    DROP COLUMN language_regex;
 #1091 column not found
After delete this code installation continue, but "Admin settings" steep is empty

**Comment by ustoopia** [comment] 2023-07-01 17:33
I was hoping for a solution in this thread. Because the same thing happens with me when trying to install it on Ubuntu 22.04/Apache/PHP8.1-fpm.

When the installer is on the page that creates the database tables, it brings me back to the first page of the installer. The table entries are succesfully added to the db. But when I start the installer again, it stops on the page that wants to write the tables to the DB, with the following error in my error.log:
**[Sat Jul 01 19:22:39.278460 2023] [proxy_fcgi:error] [pid 4125372:tid 140204845200960] [client 192.168.2.20:9635] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'cb_action_log' already exists in /var/www/web55/web/cb_install/ajax.php:101\nStack trace:\n#0 /var/www/web55/web/cb_install/ajax.php(101): mysqli_query()\n#1 {main}\n  thrown in /var/www/web55/web/cb_install/ajax.php on line 101', referer: https://mydomain.nl/cb_install/**
THe page keeps hanging on the Creating database structure... message. Tried it several times now, also with clearing out the DB in between or trying other prefixes. I can't seem to get passed the page that creates the tables. Either because it sends me back to the first page of the installer whenever the DB is empty. And when the entries are already in DB, then it hangs and the mentioned error appears in logs. Also tried other PHP versions but except from the formatting of the error message, it goes exactly the same in all cases.

**Comment by MacWarrior** [comment] 2023-07-03 07:13
Hello @ustoopia,

SQL error is because installation has already been done
Issue is related with 'infinite installation loop' which is caused by a JS anomaly : 
- What browser did you used ?
- Do you have any browser extension installed ?
- What is your antivirus ?

Thanks by advance,
Best regards,
MacWarrior.

**Comment by ustoopia** [comment] 2023-07-03 14:08
> Hello @ustoopia,
> 
> SQL error is because installation has already been done Issue is related with 'infinite installation loop' which is caused by a JS anomaly :
> 
>     * What browser did you used ?
> 
>     * Do you have any browser extension installed ?
> 
>     * What is your antivirus ?
> 
> 
> Thanks by advance, Best regards, MacWarrior.

That would be firefox
Extensions: Voila, Terabox, bitwarden, gesturefy, remote switch for pi-hole, Whatruns, DuckDuckGo privacy essentials
I use Sophos antivirus on my desktop and my UTM is also from Sophos.

I hope this information is of any use. I have never before shared what extensions I use in Firefox, so this is starting to feel really intimate :-)

**Comment by MacWarrior** [comment] 2023-07-03 15:12
Hi @ustoopia, 

Thanks for reply, with all these details we'll try to reproduce what's exactly happening during installation

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment] 2024-01-11 09:46
Hello @ustoopia,

Unfortunately, we haven't been able to reproduce issue with provided informations 😢 
Without updates for a long time, I close this issue.

Please try out latests revisions, tons of fixes have been done since and we hope would fix your issue.
If not, don't hesitate to create a new issue.

Best regards,
MacWarrior.

**Closed by MacWarrior** 2024-01-11 09:46 UTC
Labels: bug, question
