### ISSUE TITLE
Video Categories ( A technical error occurred !  )

### ISSUE THREAD

**Issue by saman-magnus** [MacWarrior/clipbucket-v5#200] opened 2022-01-18 11:05 UTC
hey bro , i have big issue here .
when i try to make new Categories i receive this error , A technical error occurred ! ... whats this for and how we can handl it ????
any idea !!!
![error](https://user-images.githubusercontent.com/41460065/149925514-57ddf8dc-3a5a-4f92-8323-f6f314e80699.png)

**Comment by MacWarrior** [comment] 2022-01-18 11:24
Hello,

Keep calm, it's gonna be allright 😉 

I reproduced the error, it's related with DB structure ; I'll make a fix today !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment] 2022-01-18 13:25
Hello @saman-magnus,

Issue has been fixed with last revision

Best regards,
MacWarrior.

**Closed by MacWarrior** 2022-01-18 13:25 UTC
Labels: bug

**Comment by saman-magnus** [comment] 2022-01-19 05:41
thank u bro, but i have sql error after update, this error code 
SQL : INSERT INTO `clipbucket `.cb_video_categories (category_name,category_desc,date_added,parent_id) VALUES ('Sport','','2022-01-19 16:18:50','0')
error ERROR : Field 'category_thumb' doesn't have a default value

**Comment by saman-magnus** [comment] 2022-01-19 06:12
i fix this one from (phpmyadmin) i change 'category_thumb' value as default (Null) its working perfectly ,
:+1: 
its a good script thank u about it but have fix issue's  
i thinking about buy a cafe for u mate :) have nice day

**Comment by MacWarrior** [comment] 2022-01-19 09:08
Hello @saman-magnus 

Text-like fields should not have default values because it's not compatible with MySQL 8+
Are you sure you updated your sources to latest revision ? Insert query should specity an empty value for category_thumb which is the right way to fix this issue

You can keep the category_thumb default value, it's not a big deal ; but can you make sure you're up-to-date and reproducing the issue without the default value ?

Best regards,
MacWarrior.

**Comment by saman-magnus** [comment] 2022-01-19 11:02
mysql version is 7.4 , it's not a big deal , i just think about auto player option :) mean videos paly each by each like youtube 
this my beta site http://farstube.com i update the video-js skin and ffmpeg but i think i have to add more option on it , anyway thank you for update this script
