### ISSUE TITLE
Cannot delete lower resolution copies of videos

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#390] opened 2024-07-20 19:20 UTC
When I go to Video File Management under Editing, I try to delete the 480p copy of a video to save space on the server. But it is not working. Nothing is getting deleted. This feature was working last month. It is broken now.
![DeleteVideo](https://github.com/user-attachments/assets/095eb52f-30bb-4a30-8b42-7031079dca0e)

**Comment by MacWarrior** [comment] 2024-07-21 18:03
Hello @SaturnTeamDev, 

Issue confirmed, but it seems to be a PHP8.X compatibility issue and it hasen't changed recently
You may have change some PHP settings or PHP version between then

I'll fix it asap, at worst tomorrow !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment] 2024-07-21 22:15
Hello @SaturnTeamDev, 

Issue has been fixed with last revision.

Best regards,
MacWarrior.

**Closed by MacWarrior** 2024-07-21 22:15 UTC
Labels: bug
