### ISSUE TITLE
Can't add a video in a collection

### ISSUE THREAD

**Issue by ecureuilfourbe** [MacWarrior/clipbucket-v5#241] opened 2022-05-17 14:59 UTC
Hi, when I try to add a video in a collection, I have this  error:

![image](https://user-images.githubusercontent.com/36704066/168842393-cf3dc1c0-e03a-464c-a386-f60a48af9b64.png)

The video works perfectly and I can add it to a playlist.

**Comment by ecureuilfourbe** [comment] 2022-05-19 12:23
Hey, where can I get the php/sql log you ask me for ?
I only have this enderneath the video, but I don't know if this is useful.
[query dev mod.txt](https://github.com/MacWarrior/clipbucket-v5/files/8729001/query.dev.mod.txt)

**Comment by ecureuilfourbe** [comment] 2022-06-13 08:23
Sorry for the late respons, I got nothing in /var/log or anywhere else.

**Comment by MacWarrior** [comment] 2022-07-29 15:43
Hello @ecureuilfourbe, 

Did you enabled dev mode ?
Can you make sure that dev mode is enabled and you have the very latest revision (5.4.1 ; REV 95 currently) ?
Can you also check your browser console ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment] 2022-08-02 14:43
Bonjour @ecureuilfourbe, 

Es-tu dispo sur Discord pour discuter de cette anomalie ?

Merci,
MacWarrior.

**Comment by ecureuilfourbe** [comment] 2022-08-08 14:40
Salut, 
l'erreur étant que la vidéo n'existe pas, j'ai vérifié les droits:
![image](https://user-images.githubusercontent.com/36704066/183443058-2149a69b-245c-4d42-8e95-0ea3d136398c.png)
à gauche une VM ubuntu 22.04 avec Clipbucket où l'ajout de la collection fonctionne:
à droite la VM mais où ça ne fonctionne pas. 

J'ai essayé de mettre les mêmes droit mais ça fonctionne pas mieux.

**Comment by MacWarrior** [comment] 2024-01-11 09:54
Hello @ecureuilfourbe, 

As we couldn't reproduce your issue, is has been a dead end for almost litterally years 😆
Please give a try on latest revisions which provide tons of fixes.

Without updated for a long time, I close this issue.
Don't hesitate to create a new one if issue persist on latest revision.

Best regards,
MacWarrior.

**Closed by MacWarrior** 2024-01-11 09:54 UTC
Labels: bug, question
