### ISSUE TITLE
when you view photos and click next photo you cant comment unless refresh page 

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#91] opened 2019-01-04 01:27 UTC
hi please test on your end this issue:

i click on photos link > then I view a photo > then click to next photo> them I try to click on comment but doesn't open? if I refresh that page then it allows for me to click on comments to open and leave a comment

thanks

Spiro

**Comment by MacWarrior** [comment] 2019-01-05 09:40
Hi,
I can't reproduce ; do you get any JS error ?
Can you provide a screenshot ?

**Comment by spirogg** [comment] 2019-01-05 22:30
![capture](https://user-images.githubusercontent.com/17736688/50729876-41545580-1107-11e9-8ac3-f5b9d90b063e.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/50729877-41545580-1107-11e9-83cc-a87355fde47b.PNG)
![capture2](https://user-images.githubusercontent.com/17736688/50729878-41545580-1107-11e9-8366-7917a20b743a.PNG)
![capture3](https://user-images.githubusercontent.com/17736688/50729879-41545580-1107-11e9-81aa-2c68dab47951.PNG)

**Comment by spirogg** [comment] 2019-01-05 22:33
i first click on photos link> then click on photo of myself then click next button then the Greece flag is there and i try to click on down **V** in comment to make a comment, it doesn't open..

**Comment by spirogg** [comment] 2019-01-05 22:36
im using centos 7 - php 7.0 because 7.2 not work for me when i try to upload photo php7.1 php7.2 wont allow for submit photo button to click

**Comment by spirogg** [comment] 2019-01-05 22:54
here is php 7.1 and 7.2 photos submit button dead

![capture](https://user-images.githubusercontent.com/17736688/50730086-99408b80-110a-11e9-9f28-17826ebccca8.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/50730087-99408b80-110a-11e9-8cee-aa80b0db9686.PNG)

**Comment by MacWarrior** [comment] 2019-01-05 23:03
Hi,

Thanks for replies ; did you check if you get any JS error in the browser console ?

**Comment by spirogg** [comment] 2019-01-05 23:09
yes i didn't get anything

![capture](https://user-images.githubusercontent.com/17736688/50730194-afe7e200-110c-11e9-80fc-d5db96602237.PNG)

**Comment by spirogg** [comment] 2019-01-05 23:14
but when only - I refresh - the option is available to leave comment

**Comment by spirogg** [comment] 2019-01-06 00:10
tried again with latest download of your repo and it still doesn't allow for drop down after click next photo

- now with edge browser console i get errors 

- see photo
![capture](https://user-images.githubusercontent.com/17736688/50730540-2be62800-1115-11e9-8ee2-4a643ae43e91.PNG)

**Comment by spirogg** [comment] 2020-06-07 09:33
@MacWarrior i tried just now and it still has the issue with the drop down to open the comment area

so I click on photos link then select a photo then click the next button then try to open the comment section but it does not open I am logged in as admin no other users are registered
just fyi 

I do not see any issues when opening the console on chrome browser latest version as of today 6/07/2020

**Comment by spirogg** [comment] 2020-06-08 02:10
@MacWarrior 
Seems this is not working because if you look at the top of the chrome tab the photo is named site maintenance 
but the photo were trying to comment on is screenshot (1) 
so there is no way its going to open the comment section because were stuck on the first photo even if we scroll right or left infinite times we still see in the chrome tab the same title of first photo we loaded when first clicking on photos 
see photo below look at tabs where I underlined the title
and then look down under the photo its name is another so the V down shaped button wont allow us to open the comment section cause it has the wrong photo in the title need to refresh page every time we click so it will show the new title and be able to comment on that photo

![button_down_not_working](https://user-images.githubusercontent.com/17736688/83986704-54261780-a903-11ea-88c5-d658a66c9914.PNG)

**Comment by MacWarrior** [comment] 2024-03-21 15:13
Hello @spirogg, 

It's been a while, but issue has finally been fixed on latest revision.

Best regards,
MacWarrior.

**Closed by MacWarrior** 2024-03-21 15:13 UTC
Labels: bug
